### ISSUE TITLE
error in i05-count-sbs.R step

### ISSUE THREAD

**Issue by Yohan-Bosse-Lab** [cancer-genomics/gemini_wflow#4]
I keep getting a message like this during the `i05-count-sbs.R `step? 

```
Error in { :
  task 4 failed - "solving row 844778: 'allow.nonnarrowing' is FALSE and the supplied end (78077249) is > refwidth"
Calls: %dopar% -> <Anonymous>
Execution halted
```

It seems to arise from this function (`IRanges::narrow() `). Do you know how to solve this?

**Comment by Yohan-Bosse-Lab** [comment]
Update: 
This seems to be due to the fact that I aligned my reads against the newer GRCh38 version of the genome. Yet, the pipeline expects .bams files aligned to the older GRCh37 genome. So using GRch37 fixes the problem, but it would be a nice improvement to the method to be able to use GRCh38 directly!

**Comment by seb951** [comment]
Update: 
This seems to be due to the fact that I aligned my reads against the GRCh38 version of the genome. Yet, the pipeline expects the genome to be aligned against GRCh37. So changing the reference genome to GRCh37 fixes the problem, yet being able to use directly the GRCh38 genome would be a nice update to the pipeline!
